// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function List(arg1) {
  return window['go']['env']['FileOp']['List'](arg1);
}

export function ListImage(arg1) {
  return window['go']['env']['FileOp']['ListImage'](arg1);
}

export function Open(arg1) {
  return window['go']['env']['FileOp']['Open'](arg1);
}

export function SelectFolder(arg1) {
  return window['go']['env']['FileOp']['SelectFolder'](arg1);
}

export function SetContext(arg1) {
  return window['go']['env']['FileOp']['SetContext'](arg1);
}
