// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {env} from '../models';
import {context} from '../models';

export function List(arg1:string):Promise<Array<env.CusFileInfo>>;

export function ListImage(arg1:string):Promise<Array<env.CusFileInfo>>;

export function Open(arg1:string):Promise<Array<number>>;

export function SelectFolder(arg1:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
