// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function List(arg1) {
  return window['go']['env']['FileOp']['List'](arg1);
}

export function ListImage(arg1) {
  return window['go']['env']['FileOp']['ListImage'](arg1);
}
