// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {env} from '../models';

export function List(arg1:string):Promise<Array<env.CusFileInfo>>;

export function ListImage(arg1:string):Promise<Array<env.CusFileInfo>>;
