// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Context() {
  return window['go']['main']['App']['Context']();
}

export function Exit() {
  return window['go']['main']['App']['Exit']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Minimises() {
  return window['go']['main']['App']['Minimises']();
}
