// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Context():Promise<context.Context>;

export function Exit():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Minimises():Promise<void>;

export function OpenUrl(arg1:string):Promise<void>;
